spring.application.name=college0
spring.datasource.url=jdbc:sqlite:primary-users.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.data.jdbc.repositories.enabled=false
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.time-zone=UTC


#spring.profiles.active=first_run